extends Node

signal color_changed(new_color: Color)
signal star_finished_emitting()
signal launch_firework()
signal request_ingredient(requestor: Node2D)
signal part_finished()
signal color_button_pressed()
signal effect_button_pressed()
signal prepare_launch()
signal firework_finished()
signal qte_clicked(data: NPC_Resource)
signal spin_finished()
signal attempt_ingredient(ing_name: String)
signal room_completed()
signal new_grain(grain: Node2D)
signal notebook_updated(npc: NPC_Resource)
signal customer_selected(npc: NPC_Resource)
signal craft_stars_completed(final_color: Color)
signal customers_cleared()
